### ISSUE TITLE
ошибки

### ISSUE THREAD

**Issue by Alecto** [TechnoFuture2020/adaptive-responsive_Grid-Flex_template#1]
в html5 нет такого синтаксиса
![image](https://user-images.githubusercontent.com/8464662/122549712-79338700-d03b-11eb-90be-d46a112cfe80.png)

разметка невалидна
![image](https://user-images.githubusercontent.com/8464662/122549898-ac761600-d03b-11eb-9362-016a112e2036.png)

соответствия макету нет, проверяйте все секции для всех разрешений попиксельно

**Comment by TechnoFuture2020** [comment]
Ошибки валидатора все исправил.
По поводу не соответствия попиксельно, так как макет в 1920px не помещался
в экран монитора и возникала горизонтальная прокрутка,
то делал pixel-perfect по обрезанному макету "1920px – croped.png" взятому
из шаблона для вёрстки.
Но этот макет был немного не подходящим по ширине, потому выставил его на
7px по координате X, чтобы макет был по середине монитора и так  проверял
вёрстку по пикселям.
Остальные размеры макета соответствуют без каких либо изысков.

Если вдруг не понятно изложил, пожалуйста посмотрите короткое 2-х минутное
видео где я показал на экране то о чём здесь написал, для большей
наглядности.
https://drive.google.com/file/d/1YAOEoAy46JlsprYWnfmJf39IMiW_5PSb/view?usp=sharing

Вот ссылка на репозиторий (в прошлой ссылке указал ветку main, а
проэкт лежит на master).
https://github.com/TechnoFuture2020/adaptive-responsive_Grid-Flex_template/tree/master

Ссылка на github pages
https://technofuture2020.github.io/adaptive-responsive_Grid-Flex_template/


пт, 18 июн. 2021 г. в 13:48, Andrey ***@***.***>:

**Comment by Alecto** [comment]
соответствия по макету нет, работа не принята.
